#!/usr/bin/env python3
"""Read-only MCP access to catalogs generated by tableau_doc.py."""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


class CatalogError(RuntimeError):
    """A user-facing catalog loading error."""


SAFE_SQL_IDENTIFIER_RE = re.compile(
    r"^[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*$"
)
SUPPORTED_AGGREGATIONS = {
    "avg",
    "count",
    "count_distinct",
    "max",
    "min",
    "sum",
}


@dataclass
class SemanticQueryService:
    config: dict[str, Any]
    base_dir: Path

    @classmethod
    def from_file(cls, path: Path) -> "SemanticQueryService":
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise CatalogError(
                f"Invalid semantic configuration {path}: {exc}"
            ) from exc
        return cls.from_config(payload, base_dir=path.parent)

    @classmethod
    def from_config(
        cls,
        payload: object,
        *,
        base_dir: Path,
    ) -> "SemanticQueryService":
        if not isinstance(payload, dict) or payload.get("version") != 1:
            raise CatalogError(
                "Semantic configuration must be an object with version 1."
            )
        datasources = payload.get("datasources")
        if not isinstance(datasources, dict) or not datasources:
            raise CatalogError(
                "Semantic configuration must define at least one datasource."
            )
        seen_names: set[str] = set()
        for datasource_name, datasource in datasources.items():
            if (
                not isinstance(datasource_name, str)
                or not datasource_name.strip()
                or datasource_name.casefold() in seen_names
            ):
                raise CatalogError(
                    f"Invalid or duplicate datasource name: {datasource_name}"
                )
            seen_names.add(datasource_name.casefold())
            cls._validate_datasource(datasource_name, datasource)
        return cls(config=payload, base_dir=base_dir)

    @staticmethod
    def _validate_datasource(name: str, datasource: object) -> None:
        if not isinstance(datasource, dict):
            raise CatalogError(f"Datasource {name} must be an object.")
        table = datasource.get("table")
        if (
            not isinstance(table, str)
            or not SAFE_SQL_IDENTIFIER_RE.fullmatch(table)
        ):
            raise CatalogError(f"Unsafe table identifier in datasource {name}.")
        connection = datasource.get("connection")
        if (
            not isinstance(connection, dict)
            or connection.get("driver") != "sqlite"
            or not isinstance(connection.get("database"), str)
            or not connection["database"]
        ):
            raise CatalogError(
                f"Datasource {name} must define a SQLite connection."
            )
        for collection_name in ("dimensions", "indicators"):
            collection = datasource.get(collection_name)
            if not isinstance(collection, dict):
                raise CatalogError(
                    f"Datasource {name} must define {collection_name}."
                )
            seen_fields: set[str] = set()
            for field_name, definition in collection.items():
                if (
                    not isinstance(field_name, str)
                    or not field_name.strip()
                    or field_name.casefold() in seen_fields
                    or not isinstance(definition, dict)
                ):
                    raise CatalogError(
                        f"Invalid {collection_name} entry in datasource {name}."
                    )
                seen_fields.add(field_name.casefold())
                column = definition.get("column")
                description = definition.get("description")
                if (
                    not isinstance(column, str)
                    or not SAFE_SQL_IDENTIFIER_RE.fullmatch(column)
                    or not isinstance(description, str)
                    or not description.strip()
                ):
                    raise CatalogError(
                        f"Invalid {field_name} definition in datasource {name}."
                    )
                if collection_name == "indicators":
                    default = definition.get("default_aggregation")
                    allowed = definition.get("allowed_aggregations")
                    if (
                        not isinstance(default, str)
                        or not isinstance(allowed, list)
                        or not allowed
                        or any(
                            not isinstance(value, str)
                            or value not in SUPPORTED_AGGREGATIONS
                            for value in allowed
                        )
                        or default not in allowed
                    ):
                        raise CatalogError(
                            f"Invalid aggregation policy for {field_name} "
                            f"in datasource {name}."
                        )

    def _datasource(self, name: str) -> tuple[str, dict[str, Any]]:
        matches = [
            (datasource_name, datasource)
            for datasource_name, datasource in self.config[
                "datasources"
            ].items()
            if datasource_name.casefold() == name.casefold()
        ]
        if len(matches) != 1:
            raise CatalogError(f"Semantic datasource not found: {name}")
        return matches[0]

    def get_dimensions(self, datasource: str) -> dict[str, Any]:
        datasource_name, definition = self._datasource(datasource)
        return {
            "datasource": datasource_name,
            "description": definition.get("description", ""),
            "dimensions": [
                {
                    "name": name,
                    "column": item["column"],
                    "description": item["description"],
                }
                for name, item in sorted(
                    definition["dimensions"].items(),
                    key=lambda pair: pair[0].casefold(),
                )
            ],
        }

    def get_indicators(self, datasource: str) -> dict[str, Any]:
        datasource_name, definition = self._datasource(datasource)
        return {
            "datasource": datasource_name,
            "description": definition.get("description", ""),
            "indicators": [
                {
                    "name": name,
                    "column": item["column"],
                    "description": item["description"],
                    "default_aggregation": item["default_aggregation"],
                    "allowed_aggregations": item[
                        "allowed_aggregations"
                    ],
                }
                for name, item in sorted(
                    definition["indicators"].items(),
                    key=lambda pair: pair[0].casefold(),
                )
            ],
        }

    @staticmethod
    def _quote_identifier(identifier: str) -> str:
        if not SAFE_SQL_IDENTIFIER_RE.fullmatch(identifier):
            raise CatalogError(f"Unsafe configured SQL identifier: {identifier}")
        return ".".join(f'"{part}"' for part in identifier.split("."))

    @staticmethod
    def _quote_alias(alias: str) -> str:
        return f'"{alias.replace(chr(34), chr(34) * 2)}"'

    @staticmethod
    def _select_named_items(
        requested: object,
        configured: dict[str, dict[str, Any]],
        *,
        kind: str,
        maximum: int,
        allow_empty: bool,
    ) -> list[tuple[str, dict[str, Any]]]:
        if (
            not isinstance(requested, list)
            or any(not isinstance(value, str) for value in requested)
            or len(requested) > maximum
            or (not allow_empty and not requested)
        ):
            raise CatalogError(
                f"{kind.title()} selection must contain between "
                f"{0 if allow_empty else 1} and {maximum} names."
            )
        configured_by_name = {
            name.casefold(): (name, definition)
            for name, definition in configured.items()
        }
        selected: list[tuple[str, dict[str, Any]]] = []
        seen: set[str] = set()
        for requested_name in requested:
            match = configured_by_name.get(requested_name.casefold())
            if match is None:
                raise CatalogError(f"Unknown {kind}: {requested_name}")
            if match[0].casefold() in seen:
                raise CatalogError(f"Duplicate {kind}: {requested_name}")
            seen.add(match[0].casefold())
            selected.append(match)
        return selected

    @staticmethod
    def _aggregate_sql(aggregation: str, column_sql: str) -> str:
        if aggregation == "count_distinct":
            return f"COUNT(DISTINCT {column_sql})"
        functions = {
            "avg": "AVG",
            "count": "COUNT",
            "max": "MAX",
            "min": "MIN",
            "sum": "SUM",
        }
        function = functions.get(aggregation)
        if function is None:
            raise CatalogError(f"Unsupported aggregation: {aggregation}")
        return f"{function}({column_sql})"

    def get_data(
        self,
        datasource: str,
        *,
        dimensions: list[str],
        indicators: list[str],
        aggregations: dict[str, str] | None = None,
        limit: int = 100,
    ) -> dict[str, Any]:
        datasource_name, definition = self._datasource(datasource)
        selected_dimensions = self._select_named_items(
            dimensions,
            definition["dimensions"],
            kind="dimension",
            maximum=10,
            allow_empty=True,
        )
        selected_indicators = self._select_named_items(
            indicators,
            definition["indicators"],
            kind="indicator",
            maximum=20,
            allow_empty=False,
        )
        if (
            isinstance(limit, bool)
            or not isinstance(limit, int)
            or not 1 <= limit <= 1000
        ):
            raise CatalogError("Query limit must be between 1 and 1000.")
        if aggregations is None:
            aggregations = {}
        if not isinstance(aggregations, dict) or any(
            not isinstance(name, str) or not isinstance(value, str)
            for name, value in aggregations.items()
        ):
            raise CatalogError("Aggregations must map indicators to policies.")

        selected_indicator_names = {
            name.casefold(): name for name, _ in selected_indicators
        }
        requested_aggregations: dict[str, str] = {}
        for requested_name, aggregation in aggregations.items():
            selected_name = selected_indicator_names.get(
                requested_name.casefold()
            )
            if selected_name is None:
                raise CatalogError(
                    f"Aggregation provided for unselected indicator: "
                    f"{requested_name}"
                )
            requested_aggregations[selected_name] = aggregation.casefold()

        select_parts: list[str] = []
        group_parts: list[str] = []
        for name, item in selected_dimensions:
            column_sql = self._quote_identifier(item["column"])
            select_parts.append(
                f"{column_sql} AS {self._quote_alias(name)}"
            )
            group_parts.append(column_sql)

        effective_aggregations: dict[str, str] = {}
        for name, item in selected_indicators:
            aggregation = requested_aggregations.get(
                name, item["default_aggregation"]
            )
            if aggregation not in item["allowed_aggregations"]:
                raise CatalogError(
                    f"Aggregation {aggregation} is not allowed for "
                    f"indicator {name}."
                )
            effective_aggregations[name] = aggregation
            expression = self._aggregate_sql(
                aggregation,
                self._quote_identifier(item["column"]),
            )
            select_parts.append(
                f"{expression} AS {self._quote_alias(name)}"
            )

        sql_parts = [
            f"SELECT {', '.join(select_parts)}",
            f"FROM {self._quote_identifier(definition['table'])}",
        ]
        if group_parts:
            sql_parts.append(f"GROUP BY {', '.join(group_parts)}")
            sql_parts.append(f"ORDER BY {', '.join(group_parts)}")
        sql_parts.append("LIMIT ?")
        sql = "\n".join(sql_parts)

        database_value = definition["connection"]["database"]
        database_path = Path(database_value)
        if not database_path.is_absolute():
            database_path = self.base_dir / database_path
        database_path = database_path.resolve()
        if not database_path.is_file():
            raise CatalogError(
                f"SQLite database does not exist for {datasource_name}."
            )
        uri = f"{database_path.as_uri()}?mode=ro"
        try:
            with sqlite3.connect(uri, uri=True) as connection:
                connection.row_factory = sqlite3.Row
                cursor = connection.execute(sql, (limit,))
                raw_rows = [dict(row) for row in cursor.fetchall()]
        except sqlite3.Error as exc:
            raise CatalogError(
                f"Query execution failed for {datasource_name}: {exc}"
            ) from exc
        rows = json.loads(
            json.dumps(raw_rows, ensure_ascii=False, default=str)
        )
        return {
            "datasource": datasource_name,
            "dimensions": [name for name, _ in selected_dimensions],
            "indicators": [name for name, _ in selected_indicators],
            "aggregations": effective_aggregations,
            "sql": sql,
            "parameters": [limit],
            "row_count": len(rows),
            "rows": rows,
        }


@dataclass
class CatalogIndex:
    workbooks: list[dict[str, Any]]
    ignored_json_files: int = 0
    warnings: list[str] = field(default_factory=list)

    @classmethod
    def load(cls, catalog_dir: Path) -> "CatalogIndex":
        if not catalog_dir.exists() or not catalog_dir.is_dir():
            raise CatalogError(f"Catalog directory does not exist: {catalog_dir}")

        workbooks: list[dict[str, Any]] = []
        ignored = 0
        warnings: list[str] = []
        for path in sorted(catalog_dir.rglob("*.json")):
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as exc:
                warnings.append(f"{path.name}: invalid JSON ({exc})")
                ignored += 1
                continue
            if not is_workbook_catalog(payload):
                ignored += 1
                continue
            workbooks.append(payload)

        if not workbooks:
            raise CatalogError(
                f"No Tableau workbook JSON catalogs found in {catalog_dir}"
            )
        workbooks.sort(key=lambda item: str(item["workbook"]).casefold())
        return cls(
            workbooks=workbooks,
            ignored_json_files=ignored,
            warnings=warnings,
        )

    def summary(self) -> dict[str, Any]:
        return {
            "workbooks": len(self.workbooks),
            "worksheets": sum(
                len(workbook["worksheets"]) for workbook in self.workbooks
            ),
            "fields": sum(len(workbook["fields"]) for workbook in self.workbooks),
            "ignored_json_files": self.ignored_json_files,
            "warnings": self.warnings,
        }

    def _workbook(self, name: str) -> dict[str, Any]:
        matches = [
            workbook
            for workbook in self.workbooks
            if str(workbook["workbook"]).casefold() == name.casefold()
        ]
        if len(matches) != 1:
            raise CatalogError(f"Workbook not found: {name}")
        return matches[0]

    def _field(self, workbook: dict[str, Any], name: str) -> dict[str, Any]:
        matches = [
            item
            for item in workbook["fields"]
            if str(item.get("caption", "")).casefold() == name.casefold()
            or str(item.get("internal_name", "")).casefold() == name.casefold()
        ]
        if not matches:
            raise CatalogError(
                f"Field not found in {workbook['workbook']}: {name}"
            )
        if len(matches) > 1:
            datasources = sorted(
                str(item.get("datasource", "Unknown")) for item in matches
            )
            raise CatalogError(
                f"Ambiguous field in {workbook['workbook']}: {name}. "
                f"Datasources: {', '.join(datasources)}"
            )
        return matches[0]

    def search(
        self,
        query: str,
        *,
        entity_type: str = "all",
        workbook: str | None = None,
        limit: int = 10,
    ) -> dict[str, Any]:
        if not query.strip():
            raise CatalogError("Search query must not be empty.")
        if entity_type not in {"all", "field", "worksheet", "workbook"}:
            raise CatalogError(f"Unsupported entity type: {entity_type}")
        if not 1 <= limit <= 50:
            raise CatalogError("Search limit must be between 1 and 50.")

        needle = query.casefold()
        selected_workbooks = (
            [self._workbook(workbook)] if workbook else self.workbooks
        )
        matches: list[dict[str, Any]] = []
        for item in selected_workbooks:
            workbook_name = str(item["workbook"])
            if entity_type in {"all", "workbook"} and needle in workbook_name.casefold():
                matches.append(
                    {
                        "entity_type": "workbook",
                        "workbook": workbook_name,
                        "name": workbook_name,
                        "worksheet_count": len(item["worksheets"]),
                        "field_count": len(item["fields"]),
                    }
                )
            if entity_type in {"all", "field"}:
                for field_item in item["fields"]:
                    searchable = " ".join(
                        [
                            str(field_item.get("caption", "")),
                            str(field_item.get("internal_name", "")),
                            str(field_item.get("datasource", "")),
                        ]
                    ).casefold()
                    if needle not in searchable:
                        continue
                    matches.append(
                        {
                            "entity_type": "field",
                            "workbook": workbook_name,
                            "name": field_item.get("caption"),
                            "type": field_item.get("type"),
                            "classification": field_item.get("classification"),
                            "impact_count": len(field_item.get("impacts", []))
                            + len(
                                field_item.get("cross_workbook_impacts", [])
                            ),
                        }
                    )
            if entity_type in {"all", "worksheet"}:
                for worksheet_item in item["worksheets"]:
                    worksheet_name = str(worksheet_item.get("name", ""))
                    if needle not in worksheet_name.casefold():
                        continue
                    matches.append(
                        {
                            "entity_type": "worksheet",
                            "workbook": workbook_name,
                            "name": worksheet_name,
                            "calculated_field_count": len(
                                worksheet_item.get("calculated_fields", [])
                            ),
                            "filter_count": len(
                                worksheet_item.get("filters", [])
                            ),
                        }
                    )
        order = {"field": 0, "worksheet": 1, "workbook": 2}
        matches.sort(
            key=lambda item: (
                order[str(item["entity_type"])],
                str(item["workbook"]).casefold(),
                str(item["name"]).casefold(),
            )
        )
        return {
            "query": query,
            "count": min(len(matches), limit),
            "truncated": len(matches) > limit,
            "results": matches[:limit],
        }

    def get_field_impact(
        self,
        workbook: str,
        field_name: str,
    ) -> dict[str, Any]:
        workbook_item = self._workbook(workbook)
        item = self._field(workbook_item, field_name)
        impacts = item.get("impacts", [])
        return {
            "workbook": workbook_item["workbook"],
            "field": item.get("caption"),
            "type": item.get("type"),
            "classification": item.get("classification"),
            "formula": item.get("display_formula"),
            "dependencies": item.get("dependencies", []),
            "dependents": item.get("dependents", []),
            "direct_worksheets": sorted(
                impact["worksheet"]
                for impact in impacts
                if impact.get("impact") == "direct"
            ),
            "indirect_impacts": [
                impact
                for impact in impacts
                if impact.get("impact") == "indirect"
            ],
            "cross_workbook_impacts": item.get(
                "cross_workbook_impacts", []
            ),
            "warnings": item.get("warnings", []),
        }

    def get_worksheet(
        self,
        workbook: str,
        worksheet: str,
    ) -> dict[str, Any]:
        workbook_item = self._workbook(workbook)
        matches = [
            item
            for item in workbook_item["worksheets"]
            if str(item.get("name", "")).casefold() == worksheet.casefold()
        ]
        if len(matches) != 1:
            raise CatalogError(
                f"Worksheet not found in {workbook_item['workbook']}: {worksheet}"
            )
        item = matches[0]
        return {
            "workbook": workbook_item["workbook"],
            "worksheet": item.get("name"),
            "filters": item.get("filters", []),
            "calculated_fields": item.get("calculated_fields", []),
            "direct_fields": item.get("direct_fields", []),
            "warnings": item.get("warnings", []),
        }

    def get_metric_contract(
        self,
        workbook: str,
        metric: str,
    ) -> dict[str, Any]:
        workbook_item = self._workbook(workbook)
        matches = [
            item
            for item in workbook_item.get("metric_contracts", [])
            if str(item.get("metric", "")).casefold() == metric.casefold()
            or str(item.get("internal_name", "")).casefold()
            == metric.casefold()
        ]
        if len(matches) != 1:
            raise CatalogError(
                f"Metric contract not found in "
                f"{workbook_item['workbook']}: {metric}"
            )
        return {
            "workbook": workbook_item["workbook"],
            **matches[0],
        }

    def trace_dependencies(
        self,
        workbook: str,
        field_name: str,
        *,
        direction: str = "upstream",
        max_depth: int = 2,
    ) -> dict[str, Any]:
        if direction not in {"upstream", "downstream"}:
            raise CatalogError("Direction must be upstream or downstream.")
        if not 1 <= max_depth <= 10:
            raise CatalogError("max_depth must be between 1 and 10.")
        workbook_item = self._workbook(workbook)
        start = self._field(workbook_item, field_name)
        by_caption = {
            str(item.get("caption")): item for item in workbook_item["fields"]
        }
        relation = "dependencies" if direction == "upstream" else "dependents"
        start_name = str(start["caption"])
        queue: list[tuple[str, int]] = [(start_name, 0)]
        visited = {start_name}
        nodes = [{"name": start_name, "depth": 0}]
        edges: list[dict[str, str]] = []
        truncated = False
        while queue:
            current_name, depth = queue.pop(0)
            current = by_caption.get(current_name)
            related = list(current.get(relation, [])) if current else []
            if depth >= max_depth:
                truncated = truncated or bool(related)
                continue
            for related_name in related:
                edges.append({"from": current_name, "to": related_name})
                if related_name in visited:
                    continue
                visited.add(related_name)
                nodes.append({"name": related_name, "depth": depth + 1})
                queue.append((related_name, depth + 1))
        return {
            "workbook": workbook_item["workbook"],
            "field": start_name,
            "direction": direction,
            "max_depth": max_depth,
            "nodes": nodes,
            "edges": edges,
            "truncated": truncated,
        }


def is_workbook_catalog(payload: object) -> bool:
    return (
        isinstance(payload, dict)
        and payload.get("schema_version") == 1
        and isinstance(payload.get("workbook"), str)
        and isinstance(payload.get("worksheets"), list)
        and isinstance(payload.get("fields"), list)
    )


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Serve Tableau reverse-engineering catalogs over MCP."
    )
    parser.add_argument(
        "--catalog",
        required=True,
        type=Path,
        help="directory containing <Workbook>.json catalogs",
    )
    parser.add_argument(
        "--semantic-config",
        type=Path,
        help=(
            "JSON configuration for validated dimensions, indicators, "
            "aggregation policies, and SQL access"
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate catalogs and print a summary without starting MCP",
    )
    return parser


def create_mcp_server(
    catalog: CatalogIndex,
    semantic_queries: SemanticQueryService | None = None,
) -> Any:
    try:
        from mcp.server.fastmcp import FastMCP
    except ImportError as exc:
        raise CatalogError(
            "The optional MCP SDK is not installed. "
            "Run: pip install -r requirements-mcp.txt"
        ) from exc

    server = FastMCP(
        "Tableau Reverse-Engineering Catalog",
        instructions=(
            "Read-only access to Tableau calculated fields, worksheet filters, "
            "dependency lineage, change impact, and configured semantic data. "
            "Use get_dimensions and get_indicators before get_data. Prefer "
            "search_catalog before requesting Tableau details when workbook or "
            "field names are uncertain."
        ),
    )

    def require_semantic_queries() -> SemanticQueryService:
        if semantic_queries is None:
            raise CatalogError(
                "Semantic query tools require --semantic-config."
            )
        return semantic_queries

    @server.tool()
    def search_catalog(
        query: str,
        entity_type: str = "all",
        workbook: str | None = None,
        limit: int = 10,
    ) -> dict[str, Any]:
        """Search workbooks, worksheets, and fields with bounded results."""
        return catalog.search(
            query,
            entity_type=entity_type,
            workbook=workbook,
            limit=limit,
        )

    @server.tool()
    def get_field_impact(
        workbook: str,
        field: str,
    ) -> dict[str, Any]:
        """Get direct and indirect worksheet impact for one field."""
        return catalog.get_field_impact(workbook, field)

    @server.tool()
    def get_worksheet(
        workbook: str,
        worksheet: str,
    ) -> dict[str, Any]:
        """Get filters, direct fields, and calculations for one worksheet."""
        return catalog.get_worksheet(workbook, worksheet)

    @server.tool()
    def get_metric_contract(
        workbook: str,
        metric: str,
    ) -> dict[str, Any]:
        """Get the semantic recipe and Tableau contexts for one metric."""
        return catalog.get_metric_contract(workbook, metric)

    @server.tool()
    def get_dimensions(datasource: str) -> dict[str, Any]:
        """List configured dimensions with descriptions for one datasource."""
        return require_semantic_queries().get_dimensions(datasource)

    @server.tool()
    def get_indicators(datasource: str) -> dict[str, Any]:
        """List indicators with descriptions and aggregation policies."""
        return require_semantic_queries().get_indicators(datasource)

    @server.tool()
    def get_data(
        datasource: str,
        dimensions: list[str],
        indicators: list[str],
        aggregations: dict[str, str] | None = None,
        limit: int = 100,
    ) -> dict[str, Any]:
        """Run a bounded query compiled only from validated semantic inputs."""
        return require_semantic_queries().get_data(
            datasource,
            dimensions=dimensions,
            indicators=indicators,
            aggregations=aggregations,
            limit=limit,
        )

    @server.tool()
    def trace_dependencies(
        workbook: str,
        field: str,
        direction: str = "upstream",
        max_depth: int = 2,
    ) -> dict[str, Any]:
        """Trace bounded upstream dependencies or downstream dependents."""
        return catalog.trace_dependencies(
            workbook,
            field,
            direction=direction,
            max_depth=max_depth,
        )

    return server


def run(args: argparse.Namespace) -> int:
    catalog = CatalogIndex.load(args.catalog)
    semantic_queries = (
        SemanticQueryService.from_file(args.semantic_config)
        if args.semantic_config
        else None
    )
    if args.check:
        summary = catalog.summary()
        summary["semantic_configured"] = semantic_queries is not None
        summary["semantic_datasources"] = (
            len(semantic_queries.config["datasources"])
            if semantic_queries
            else 0
        )
        print(json.dumps(summary, ensure_ascii=False, indent=2))
        return 0
    server = create_mcp_server(catalog, semantic_queries)
    server.run(transport="stdio")
    return 0


def main() -> int:
    parser = build_argument_parser()
    args = parser.parse_args()
    try:
        return run(args)
    except CatalogError as exc:
        parser.error(str(exc))
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
