#!/usr/bin/env python3
"""Read-only MCP access to catalogs generated by tableau_doc.py."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


class CatalogError(RuntimeError):
    """A user-facing catalog loading error."""


@dataclass
class CatalogIndex:
    workbooks: list[dict[str, Any]]
    ignored_json_files: int = 0
    warnings: list[str] = field(default_factory=list)

    @classmethod
    def load(cls, catalog_dir: Path) -> "CatalogIndex":
        if not catalog_dir.exists() or not catalog_dir.is_dir():
            raise CatalogError(f"Catalog directory does not exist: {catalog_dir}")

        workbooks: list[dict[str, Any]] = []
        ignored = 0
        warnings: list[str] = []
        for path in sorted(catalog_dir.rglob("*.json")):
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as exc:
                warnings.append(f"{path.name}: invalid JSON ({exc})")
                ignored += 1
                continue
            if not is_workbook_catalog(payload):
                ignored += 1
                continue
            workbooks.append(payload)

        if not workbooks:
            raise CatalogError(
                f"No Tableau workbook JSON catalogs found in {catalog_dir}"
            )
        workbooks.sort(key=lambda item: str(item["workbook"]).casefold())
        return cls(
            workbooks=workbooks,
            ignored_json_files=ignored,
            warnings=warnings,
        )

    def summary(self) -> dict[str, Any]:
        return {
            "workbooks": len(self.workbooks),
            "worksheets": sum(
                len(workbook["worksheets"]) for workbook in self.workbooks
            ),
            "fields": sum(len(workbook["fields"]) for workbook in self.workbooks),
            "ignored_json_files": self.ignored_json_files,
            "warnings": self.warnings,
        }

    def _workbook(self, name: str) -> dict[str, Any]:
        matches = [
            workbook
            for workbook in self.workbooks
            if str(workbook["workbook"]).casefold() == name.casefold()
        ]
        if len(matches) != 1:
            raise CatalogError(f"Workbook not found: {name}")
        return matches[0]

    def _field(self, workbook: dict[str, Any], name: str) -> dict[str, Any]:
        matches = [
            item
            for item in workbook["fields"]
            if str(item.get("caption", "")).casefold() == name.casefold()
            or str(item.get("internal_name", "")).casefold() == name.casefold()
        ]
        if not matches:
            raise CatalogError(
                f"Field not found in {workbook['workbook']}: {name}"
            )
        if len(matches) > 1:
            datasources = sorted(
                str(item.get("datasource", "Unknown")) for item in matches
            )
            raise CatalogError(
                f"Ambiguous field in {workbook['workbook']}: {name}. "
                f"Datasources: {', '.join(datasources)}"
            )
        return matches[0]

    def search(
        self,
        query: str,
        *,
        entity_type: str = "all",
        workbook: str | None = None,
        limit: int = 10,
    ) -> dict[str, Any]:
        if not query.strip():
            raise CatalogError("Search query must not be empty.")
        if entity_type not in {"all", "field", "worksheet", "workbook"}:
            raise CatalogError(f"Unsupported entity type: {entity_type}")
        if not 1 <= limit <= 50:
            raise CatalogError("Search limit must be between 1 and 50.")

        needle = query.casefold()
        selected_workbooks = (
            [self._workbook(workbook)] if workbook else self.workbooks
        )
        matches: list[dict[str, Any]] = []
        for item in selected_workbooks:
            workbook_name = str(item["workbook"])
            if entity_type in {"all", "workbook"} and needle in workbook_name.casefold():
                matches.append(
                    {
                        "entity_type": "workbook",
                        "workbook": workbook_name,
                        "name": workbook_name,
                        "worksheet_count": len(item["worksheets"]),
                        "field_count": len(item["fields"]),
                    }
                )
            if entity_type in {"all", "field"}:
                for field_item in item["fields"]:
                    searchable = " ".join(
                        [
                            str(field_item.get("caption", "")),
                            str(field_item.get("internal_name", "")),
                            str(field_item.get("datasource", "")),
                        ]
                    ).casefold()
                    if needle not in searchable:
                        continue
                    matches.append(
                        {
                            "entity_type": "field",
                            "workbook": workbook_name,
                            "name": field_item.get("caption"),
                            "type": field_item.get("type"),
                            "classification": field_item.get("classification"),
                            "impact_count": len(field_item.get("impacts", []))
                            + len(
                                field_item.get("cross_workbook_impacts", [])
                            ),
                        }
                    )
            if entity_type in {"all", "worksheet"}:
                for worksheet_item in item["worksheets"]:
                    worksheet_name = str(worksheet_item.get("name", ""))
                    if needle not in worksheet_name.casefold():
                        continue
                    matches.append(
                        {
                            "entity_type": "worksheet",
                            "workbook": workbook_name,
                            "name": worksheet_name,
                            "calculated_field_count": len(
                                worksheet_item.get("calculated_fields", [])
                            ),
                            "filter_count": len(
                                worksheet_item.get("filters", [])
                            ),
                        }
                    )
        order = {"field": 0, "worksheet": 1, "workbook": 2}
        matches.sort(
            key=lambda item: (
                order[str(item["entity_type"])],
                str(item["workbook"]).casefold(),
                str(item["name"]).casefold(),
            )
        )
        return {
            "query": query,
            "count": min(len(matches), limit),
            "truncated": len(matches) > limit,
            "results": matches[:limit],
        }

    def get_field_impact(
        self,
        workbook: str,
        field_name: str,
    ) -> dict[str, Any]:
        workbook_item = self._workbook(workbook)
        item = self._field(workbook_item, field_name)
        impacts = item.get("impacts", [])
        return {
            "workbook": workbook_item["workbook"],
            "field": item.get("caption"),
            "type": item.get("type"),
            "classification": item.get("classification"),
            "formula": item.get("display_formula"),
            "dependencies": item.get("dependencies", []),
            "dependents": item.get("dependents", []),
            "direct_worksheets": sorted(
                impact["worksheet"]
                for impact in impacts
                if impact.get("impact") == "direct"
            ),
            "indirect_impacts": [
                impact
                for impact in impacts
                if impact.get("impact") == "indirect"
            ],
            "cross_workbook_impacts": item.get(
                "cross_workbook_impacts", []
            ),
            "warnings": item.get("warnings", []),
        }

    def get_worksheet(
        self,
        workbook: str,
        worksheet: str,
    ) -> dict[str, Any]:
        workbook_item = self._workbook(workbook)
        matches = [
            item
            for item in workbook_item["worksheets"]
            if str(item.get("name", "")).casefold() == worksheet.casefold()
        ]
        if len(matches) != 1:
            raise CatalogError(
                f"Worksheet not found in {workbook_item['workbook']}: {worksheet}"
            )
        item = matches[0]
        return {
            "workbook": workbook_item["workbook"],
            "worksheet": item.get("name"),
            "filters": item.get("filters", []),
            "calculated_fields": item.get("calculated_fields", []),
            "direct_fields": item.get("direct_fields", []),
            "warnings": item.get("warnings", []),
        }

    def get_metric_contract(
        self,
        workbook: str,
        metric: str,
    ) -> dict[str, Any]:
        workbook_item = self._workbook(workbook)
        matches = [
            item
            for item in workbook_item.get("metric_contracts", [])
            if str(item.get("metric", "")).casefold() == metric.casefold()
            or str(item.get("internal_name", "")).casefold()
            == metric.casefold()
        ]
        if len(matches) != 1:
            raise CatalogError(
                f"Metric contract not found in "
                f"{workbook_item['workbook']}: {metric}"
            )
        return {
            "workbook": workbook_item["workbook"],
            **matches[0],
        }

    def trace_dependencies(
        self,
        workbook: str,
        field_name: str,
        *,
        direction: str = "upstream",
        max_depth: int = 2,
    ) -> dict[str, Any]:
        if direction not in {"upstream", "downstream"}:
            raise CatalogError("Direction must be upstream or downstream.")
        if not 1 <= max_depth <= 10:
            raise CatalogError("max_depth must be between 1 and 10.")
        workbook_item = self._workbook(workbook)
        start = self._field(workbook_item, field_name)
        by_caption = {
            str(item.get("caption")): item for item in workbook_item["fields"]
        }
        relation = "dependencies" if direction == "upstream" else "dependents"
        start_name = str(start["caption"])
        queue: list[tuple[str, int]] = [(start_name, 0)]
        visited = {start_name}
        nodes = [{"name": start_name, "depth": 0}]
        edges: list[dict[str, str]] = []
        truncated = False
        while queue:
            current_name, depth = queue.pop(0)
            current = by_caption.get(current_name)
            related = list(current.get(relation, [])) if current else []
            if depth >= max_depth:
                truncated = truncated or bool(related)
                continue
            for related_name in related:
                edges.append({"from": current_name, "to": related_name})
                if related_name in visited:
                    continue
                visited.add(related_name)
                nodes.append({"name": related_name, "depth": depth + 1})
                queue.append((related_name, depth + 1))
        return {
            "workbook": workbook_item["workbook"],
            "field": start_name,
            "direction": direction,
            "max_depth": max_depth,
            "nodes": nodes,
            "edges": edges,
            "truncated": truncated,
        }


def is_workbook_catalog(payload: object) -> bool:
    return (
        isinstance(payload, dict)
        and payload.get("schema_version") == 1
        and isinstance(payload.get("workbook"), str)
        and isinstance(payload.get("worksheets"), list)
        and isinstance(payload.get("fields"), list)
    )


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Serve Tableau reverse-engineering catalogs over MCP."
    )
    parser.add_argument(
        "--catalog",
        required=True,
        type=Path,
        help="directory containing <Workbook>.json catalogs",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate catalogs and print a summary without starting MCP",
    )
    return parser


def create_mcp_server(catalog: CatalogIndex) -> Any:
    try:
        from mcp.server.fastmcp import FastMCP
    except ImportError as exc:
        raise CatalogError(
            "The optional MCP SDK is not installed. "
            "Run: pip install -r requirements-mcp.txt"
        ) from exc

    server = FastMCP(
        "Tableau Reverse-Engineering Catalog",
        instructions=(
            "Read-only access to Tableau calculated fields, worksheet filters, "
            "dependency lineage, and change impact. Prefer search_catalog before "
            "requesting details when workbook or field names are uncertain."
        ),
    )

    @server.tool()
    def search_catalog(
        query: str,
        entity_type: str = "all",
        workbook: str | None = None,
        limit: int = 10,
    ) -> dict[str, Any]:
        """Search workbooks, worksheets, and fields with bounded results."""
        return catalog.search(
            query,
            entity_type=entity_type,
            workbook=workbook,
            limit=limit,
        )

    @server.tool()
    def get_field_impact(
        workbook: str,
        field: str,
    ) -> dict[str, Any]:
        """Get direct and indirect worksheet impact for one field."""
        return catalog.get_field_impact(workbook, field)

    @server.tool()
    def get_worksheet(
        workbook: str,
        worksheet: str,
    ) -> dict[str, Any]:
        """Get filters, direct fields, and calculations for one worksheet."""
        return catalog.get_worksheet(workbook, worksheet)

    @server.tool()
    def get_metric_contract(
        workbook: str,
        metric: str,
    ) -> dict[str, Any]:
        """Get the semantic recipe and Tableau contexts for one metric."""
        return catalog.get_metric_contract(workbook, metric)

    @server.tool()
    def trace_dependencies(
        workbook: str,
        field: str,
        direction: str = "upstream",
        max_depth: int = 2,
    ) -> dict[str, Any]:
        """Trace bounded upstream dependencies or downstream dependents."""
        return catalog.trace_dependencies(
            workbook,
            field,
            direction=direction,
            max_depth=max_depth,
        )

    return server


def run(args: argparse.Namespace) -> int:
    catalog = CatalogIndex.load(args.catalog)
    if args.check:
        print(json.dumps(catalog.summary(), ensure_ascii=False, indent=2))
        return 0
    server = create_mcp_server(catalog)
    server.run(transport="stdio")
    return 0


def main() -> int:
    parser = build_argument_parser()
    args = parser.parse_args()
    try:
        return run(args)
    except CatalogError as exc:
        parser.error(str(exc))
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
